---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: parallel
spec:
  params:
    - name: message
      type: string
    - name: url
      type: string
  workspaces:
    - name: this-workspace
  tasks:
  - name: ls
    taskRef:
      name: task-ls

  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: source
      workspace: this-workspace
    params:
    - name: url
      value: $(params.url)
    runAfter:
      - ls

  - name: sleep-a
    taskRef:
      name: task-sleep
    runAfter:
     - ls

  - name: sleep-b
    taskRef:
      name: task-sleep
    runAfter:
     - ls

  - name: echo
    taskRef:
      name: task-echo
    #params:
    #- name: message
    #  value: Finishing the pipeline jjjj
    params:
    - name: message
      value: $(params.message)
    workspaces:
    - name: source
      workspace: this-workspace
    runAfter:
     - sleep-a
     - sleep-b
     - git-clone

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-ls
spec:
  steps:
  - name: ls
    image: alpine:latest
    command: [ls]
    args: ["-l", "/"]

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-sleep
spec:
  steps:
  - name: sleep
    image: alpine:latest
    script: |
      echo Starting to sleep...
      sleep 10
      echo Finished sleeping

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-echo
spec:
  params:
  - name: message
    type: string
  workspaces:
  - name: source
  steps:
  - name: echo
    image: alpine:latest
    #command: [echo]
    #args: ["$(params.message)"]
    script: |
      cd $(workspaces.source.path)
      ls -al 
      echo ""
      echo ""
      echo $(params.message)
      cat date

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
  - name: source
  params:
  - name: url
    type: string
  steps:
  - name: clone
    image: alpine/git:v2.49.1
    script: |
      cd $(workspaces.source.path)
      ls -la 
      echo ""
      echo "removing everything"
      rm -rf tools
      git clone -v $(params.url)
      pwd
      echo $(date) > date
      cat date
