apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build
  namespace: one
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
